# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drmas',
            name='schedule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='clinic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='profile',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='specialty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
