# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0002_auto_20170127_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmas',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='prefix',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='abrev',
            field=models.CharField(max_length=20),
        ),
    ]
