# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0004_auto_20170128_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmas',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
