# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0006_auto_20170128_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmas',
            name='clinic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='drCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='prefix',
            field=models.CharField(blank=True, default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='profile',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='schedule',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='specialty',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='abrev',
            field=models.CharField(max_length=10),
        ),
    ]
