# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0007_auto_20170129_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmas',
            name='clinic',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='drCode',
            field=models.CharField(blank=True, default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='firstname',
            field=models.CharField(default=b'\xe0\xb8\xad\xe0\xb8\xa0\xe0\xb8\xb4\xe0\xb8\xa1\xe0\xb8\xb8\xe0\xb8\x82', max_length=50),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='lastname',
            field=models.CharField(default=b'\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\xa7\xe0\xb8\x87', max_length=50),
        ),
        migrations.AlterField(
            model_name='drmas',
            name='prefix',
            field=models.CharField(blank=True, default=b'\xe0\xb8\x84\xe0\xb8\xb8\xe0\xb8\x93', max_length=10),
        ),
    ]
